apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-production
  labels:
    app: app-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-production
  template:
    metadata:
      labels:
        app: app-production
    spec:
      containers:
      - name: container
        image: "ghcr.io/get-glu/gitops-example/app:latest@sha256:e45af70591e3cb95e8d3b90f2b9807bc9f7a948c23094b38361f362d1dfb24ab"
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENVIRONMENT
          value: "production"
        - name: APP_IMAGE_DIGEST
          value: "sha256:e45af70591e3cb95e8d3b90f2b9807bc9f7a948c23094b38361f362d1dfb24ab"
