apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-staging
  labels:
    app: app-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-staging
  template:
    metadata:
      labels:
        app: app-staging
    spec:
      containers:
      - name: container
        image: ghcr.io/get-glu/gitops-example/app:latest
        ports:
        - containerPort: 8080
