apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-staging
  name: example-app-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-staging
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-staging
    spec:
      containers:
      - env:
        - name: APP_ENVIRONMENT
          value: staging
        - name: APP_IMAGE_DIGEST
          value: sha256:180dea3f897f4fcbb098f04b4664b67e6550e91c984e7aff8001c7eacd657855
        image: ghcr.io/get-glu/gitops-example/app@sha256:180dea3f897f4fcbb098f04b4664b67e6550e91c984e7aff8001c7eacd657855
        name: container
        ports:
        - containerPort: 8080
        resources: {}
status: {}
